name: Optimization Benchmarking
rooturl: https://optimizationbenchmarking.github.io
baseurl: /documentation-examples
include: [.txt,.zip,.xml]
authorName: Thomas Weise
authorEmail: tweise@ustc.edu.cn
timezone: Asia/Shanghai
encoding: utf-8
guiVersion: 0.8.5
cliVersion: 0.8.5
